# Generated by Django 3.2.2 on 2021-05-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
