# Generated by Django 3.2.2 on 2021-05-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('l', 'l'), ('ml', 'ml'), ('kg', 'kg'), ('g', 'g'), ('mg', 'mg'), ('item', 'item')], max_length=50),
        ),
    ]
