# Generated by Django 3.2.2 on 2021-05-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('products', '0007_auto_20210516_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='city',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='country',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='full_name',
            field=models.CharField(default='test testoff', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='phone',
            field=models.CharField(default='867615800', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='state',
            field=models.CharField(default='Alabama', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='zip_code',
            field=models.CharField(default=12345, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='sessions.session'),
        ),
    ]
