# Generated by Django 3.2.2 on 2021-05-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('products', '0008_auto_20210524_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sessions.session'),
        ),
    ]
